IssueTracker/Models/Employees/GetEmployeesResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IssueTracker.Models.Employees
{
    public class GetEmployeesResponse
    {
        public IList<GetEmployeeSummaryItem> Employees { get; set; }
        public int NumberOfFullTimeEmployees { get; set; }
    }

    public class GetEmployeeSummaryItem
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
    }
}

IssueTracker/Models/Employees/PostEmployeeRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IssueTracker.Models.Employees
{
    public class PostEmployeeRequest : IValidatableObject
    {
        [Required]
        public string FirstName { get; set; }
        [Required][StringLength(50)]
        public string LastName { get; set; }
        [Range(25000, 500000)]
        public decimal StartingSalary { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
           if(FirstName.ToLower() == "darth" && LastName.ToLower() == "vader")
            {
                yield return new ValidationResult("This violates our strict no Sith policy");
            }
        }
    }
}

IssueTracker/Models/ErrorViewModel.cs
using System;

namespace IssueTracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IssueTracker/Controllers/EmployeesController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using IssueTracker.Domain;
using IssueTracker.Models.Employees;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IssueTracker.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IssueTrackerDataContext _context;
        private readonly IMapper _mapper;
        private readonly MapperConfiguration _config;

        public EmployeesController(IssueTrackerDataContext context, IMapper mapper, MapperConfiguration config)
        {
            _context = context;
            _mapper = mapper;
            _config = config;
        }



        // GET /employees  (or /employees/index)
        public async Task<IActionResult> Index()
        {
            var response = new GetEmployeesResponse();

            var data = await _context.Employees
                .OrderBy(e => e.LastName)
                .ProjectTo<GetEmployeeSummaryItem>(_config)
                .ToListAsync();

            response.NumberOfFullTimeEmployees = data.Count();
            response.Employees = data;
            return View(response);
        }

        public IActionResult New()
        {
            var model = new PostEmployeeRequest();
            model.StartingSalary = 35000;
            return View(model);
        }

        public async Task<IActionResult> CreateAsync(PostEmployeeRequest request)
        {
            if(!ModelState.IsValid)
            {
                return View("New", request);
            } else
            {
                // uh, we should save it to the database...
                var employee = new Employee
                {
                    FirstName = request.FirstName,
                    LastName = request.LastName,
                    Email = $"{request.FirstName.ToLower()}@aol.com",
                    Salary = request.StartingSalary
                };

                _context.Employees.Add(employee);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
        }
    }
}

IssueTracker/Controllers/HomeController.cs
using IssueTracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace IssueTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IssueTracker/Views/Employees/Index.cshtml
@model GetEmployeesResponse
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
} 

<h2>Employees Rock!</h2>

@foreach(var employee in Model.Employees)
            {
                <div>
                    <p>@employee.FullName</p>
                     <p>Email them at @employee.Email</p>
                </div>
            }

<div>
    <p>We have @Model.NumberOfFullTimeEmployees full time employees.</p>
</div>

<a class="btn btn-primary" asp-action="New" asp-controller="Employees">Hire A New Employee</a>

IssueTracker/Views/Employees/New.cshtml
@model PostEmployeeRequest
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" action="create">
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input class="form-control" asp-for="FirstName" />
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input class="form-control" asp-for="LastName" />
    </div>
    <div class="form-group">
        <label asp-for="StartingSalary"></label>
        <input class="form-control" asp-for="StartingSalary" type="number" />
    </div>
    <button class="btn btn-primary" type="submit">Hire!</button>
</form>

IssueTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To The Issue Tracker</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IssueTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IssueTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IssueTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
          
            @RenderBody()
          
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IssueTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>